### ISSUE TITLE
Не отображаются кроссы второго уровня в методе AM->findReplacements

### ISSUE THREAD

**Issue by 64j** [laximoru/guayaquillib#1]
При получении кросcов второго уровня, через метод 
**AM->findReplacements(partId, locale, crossOriginals = true),**
отображается всего один элемент, но от сервиса приходят данные в большем количестве.

Ошибка при выборе обёртки объекта SecondLevelReplacement и подстановке типа https://github.com/laximoru/guayaquillib/blob/master/src/RequestBase.php#L62

Типа должен быть array, а не single и обертка по аналогии с ListDetails https://github.com/laximoru/guayaquillib/blob/master/src/RequestBase.php#L48

Обертка может приблизительно такой вид

```php
use Exception;
use GuayaquilLib\objects\am\SecondLevelReplacement;
use GuayaquilLib\objects\BaseObject;
use SimpleXMLElement;

class SecondLevelReplacementListObject extends BaseObject
{
    /**
     * @var SecondLevelReplacement[]|array
     */
    protected array $replacements;

    /**
     * @return array
     */
    public function getReplacements(): array
    {
        return $this->replacements;
    }

    /**
     * @throws Exception
     */
    protected function fromXml(SimpleXMLElement $data)
    {
        foreach ($data as $simpleXMLElement) {
            $this->replacements[] = new SecondLevelReplacement($simpleXMLElement);
        }
    }
}
```

**Comment by laximoru** [comment]
Исправлено, спасибо
