### ISSUE TITLE
В объекте Wizard ожидается массив а приходит null

### ISSUE THREAD

**Issue by 64j** [laximoru/guayaquillib#2]
В классе   **objects/oem/WizardStepObject.php** при получении опций ожидается **массив**, но при прохождении первого шага в опции приходит **null**, и геттер падает с ошибкой не соответствия типов
https://github.com/laximoru/guayaquillib/blob/master/src/objects/oem/WizardStepObject.php#L124

Как решение

```php
    /**
     * @var WizardStepOptionObject[]|array
     */
    protected array $options = [];
```

**Comment by laximoru** [comment]
исправлено
